kind: Deployment
apiVersion: apps/v1
metadata:
  name: banana-app
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      labels:
        app: banana
    spec:
      containers:
        - name: banana-app
          image: hashicorp/http-echo
          args:
            - "-text=bananadeploy"

---

kind: Service
apiVersion: v1
metadata:
  name: banana-service
  namespace: example
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image